### ISSUE TITLE
기획

### ISSUE THREAD

**Issue by Polohodoro** [Tduggy/Starry-Arcana#35]
캐릭터(능력치, 어빌리티)
카드(카드들, 등급별로, 탐사능력까지, 몹별 특수 카드)
몬스터(계층별 몹, 보스몹, 필드보스몹, 몹별 특수 패턴
장비(무기, 방어구)
던전(네이밍, 컨셉, 각종 배율)

**Comment by pilsungk-oss** [comment]
@Polohodoro 아직 코드 개발 시작 안 한 건가요? 깃헙에 커밋이 하나도 없네요?
